version: 2
jobs:
  build:
    machine: true

    working_directory: ~/cumulus-dashboard
    steps:
      - checkout

      # restore cache
      - restore_cache:
          keys:
            - cumulusdashboard-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: docker run --rm -v /home/circleci/.cache:/root/.cache -v $(pwd):/home --workdir /home node:8.11.4 yarn install --frozen-lockfile --cache-folder /root/.cache

      # save node_module folders
      - save_cache:
          key: cumulusdashboard-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
 
      - run:
          name: Run tests
          command: docker run --rm -v /home/circleci/.cache:/root/.cache -v $(pwd):/home --workdir /home node:8.11.4 yarn test --cache-folder /root/.cache

      - run:
          name: Prepare servers 
          command: |
            # run fake api
            docker run -d --name api -v $(pwd):/home --workdir /home -p 5001:5001 node:8.11.4 node fake-api.js

            # run dashboard
            docker run -d --name dashboard -v $(pwd):/home --workdir /home -e APIROOT=http://api:5001 -p 3000:3000 node:8.11.4 yarn serve
      
      - run:
          name: Run Validation Tests
          command: docker run --link api:api --link dashboard:dashboard -e DASHBOARD_HOST=http://dashboard:3000 --rm -v /home/circleci/.cache:/root/.cache -v $(pwd):/home --workdir /home node:8.11.4 yarn validation
      
      - run:
          name: Run Integration Tests
          command: docker run --link api:api --link dashboard:dashboard -e DASHBOARD_HOST=http://dashboard:3000 --rm -v /home/circleci/.cache:/root/.cache -v $(pwd):/home --workdir /home node:8.11.4 yarn cypress-ci 