version: 2
jobs:
  build:
    docker:
      - image: developmentseed/circleci:node8.4-python2.7

    working_directory: ~/cumulus-dashboard
    steps:
      - checkout

      # restore cache
      - restore_cache:
          keys:
            - cumulusdashboard-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: |
            yarn install

      - run:
          name: Run tests
          command: yarn test

      # save node_module folders
      - save_cache:
          key: cumulusdashboard-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/cumulus-dashboard/node_modules

      - deploy:
          name: Dev Dashboard deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              yarn run build
              aws s3 sync ~/cumulus-dashboard/dist/. s3://lpdaac-cumulus-sandbox-dashboard --acl=public-read

            fi
