version: 2
jobs:
  build:
    machine: true

    working_directory: ~/cumulus-dashboard
    steps:
      - checkout

      # restore cache
      - restore_cache:
          keys:
            - cumulusdashboard-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: |
            nvm install
            nvm use
            yarn install --frozen-lockfile

      # save node_module folders
      - save_cache:
          key: cumulusdashboard-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
 
      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Prepare servers 
          command: |
            # run fake api
            docker run -d --name api -v $(pwd):/home --workdir /home -p 5001:5001 node:8.11.4 node fake-api.js

            # run dashboard
            docker run -d --name dashboard -v $(pwd):/home --workdir -e APIROOT=http://localhost:5001 /home -p 3000:3000 node:8.11.4 yarn serve
      
      - run:
          name: Run Validation Tests
          command: yarn validation 
      
      - run:
          name: Run Integration Tests
          command: yarn cypress-ci 